### ISSUE TITLE
Uncaught Error: Could not find module `ember-data/-private/system/normalize-model-name` imported from `ember-resource-metadata/private-api`

### ISSUE THREAD

**Issue by yched** [ef4/contenta_cardstack#3]
After running 'ember serve', visiting http://localhost:4200 showed a white page with the following error in console :

```
vendor.js:42242 Error: Could not find module `ember-data/-private/system/normalize-model-name` imported from `ember-resource-metadata/private-api`
    at missingModule (vendor.js:5386)
    at findModule (vendor.js:5397)
    at Module.findDeps (vendor.js:5307)
    at findModule (vendor.js:5401)
    at Module.findDeps (vendor.js:5307)
    at findModule (vendor.js:5401)
    at Module.findDeps (vendor.js:5307)
    at findModule (vendor.js:5401)
    at requireModule (vendor.js:5163)
    at Class._extractDefaultExport (vendor.js:89557)
```

As per https://github.com/emberjs/data/issues/5021#issuecomment-309463288, downgrading ember-data (yarn upgrade ember-data@2.13.2) seems to fix the issue and lets me view the app

**Comment by yched** [comment]
FWIW, apparently this is fixed in ember-resource-metadata 0.0.8,
but @cardstack/tools 2.4.0 wants ^0.0.7

@cardstack/tools master has since then removed its dep on ember-resource-metadata, which should also fix the issue, but there is no release with that yet :-)

**Comment by ef4** [comment]
cardstack master still depends on ember-resource-metadata, it has just moved around a bit (it is supposed to be a `dependency` of `@cardstack/models`). 

I just published `@cardstack/models` 0.2.5 with an update to ember-resource-metadata 0.0.8.

**Comment by yched** [comment]
@ef4 Nice !

Then I guess the package.json + yarn.lock files in the contenta_cardstack demo project here still need to be updated to point to the 0.2.5 of the various packages, to benefit from the fix ?

**Comment by ef4** [comment]
Yes, we should upgrade to the latest here.
